### ISSUE TITLE
Use explicit file names to link referenced documents

### ISSUE THREAD

**Issue by RaphaelKomander** [openintegrationhub/Data-and-Domain-Models#37]
Since we convert results into PDFs, please make sure that links show the explicit file name.

- [x] **EXAMPLE** [Master Data Models (Definitions, Rules and Regulations)](https://github.com/openintegrationhub/Data-and-Domain-Models/blob/7c5196e7c87a72ab043810b7051b3b1af28c806f/MasterDataModels/README.md) by @lashauer 
- [x] PDF links wont work for [MetaModel.md](https://github.com/openintegrationhub/Data-and-Domain-Models/blob/master/DataModels/MetaModel.md#schema-definition-language-sdl) by @lashauer 
- [ ] [/src/main/schema/addresses/shared-definitions.json](https://github.com/openintegrationhub/Data-and-Domain-Models/blob/master/MasterDataModels/MasterDataModelAdresses.md#52-json-schema-of-the-oih-master-data-model-for-addresses) by @hschmidthh 
- [ ] [/src/main/schema/addresses/relation.json](https://github.com/openintegrationhub/Data-and-Domain-Models/blob/master/MasterDataModels/MasterDataModelAdresses.md#52-json-schema-of-the-oih-master-data-model-for-addresses) by @hschmidthh 
- [ ] [/src/main/schema/addresses/organization.json](https://github.com/openintegrationhub/Data-and-Domain-Models/blob/master/MasterDataModels/MasterDataModelAdresses.md#52-json-schema-of-the-oih-master-data-model-for-addresses) by @hschmidthh 
- [ ] [/src/main/schema/addresses/person.json](https://github.com/openintegrationhub/Data-and-Domain-Models/blob/master/MasterDataModels/MasterDataModelAdresses.md#52-json-schema-of-the-oih-master-data-model-for-addresses) by @hschmidthh 
- [x] [/src/main/schema/products/product.json](https://github.com/openintegrationhub/Data-and-Domain-Models/blob/master/MasterDataModels/MasterDataModelProducts.md#42-json-schema-of-the-oih-master-data-model-for-addresses) by @JosefBraeuer
