### ISSUE TITLE
Verify the scope of standard data models

### ISSUE THREAD

**Issue by RaphaelKomander** [openintegrationhub/Data-and-Domain-Models#42]
The required attributes for the standard data model (configured domain models) arise from the data which a company uses across multiple applications. The underlying business transaction determines the scope of a data set. Such an aggregate consist of nested attributes of separate domain models.

- [ ] Ask for data that need to be exchanged
- [ ] Make a list of representative business transaction
- [ ] Identify the underlying data of most frequent cases
- [ ] Create aggregates, that allow seamless data exchange
- [ ] Derive an efficient cut for the domain model configuration
