### ISSUE TITLE
Unify the documentation for the actual prototype

### ISSUE THREAD

**Issue by RaphaelKomander** [openintegrationhub/Data-and-Domain-Models#49]
As mentioned at #65, an 'ISV-N integration flow' should be convenient to create. So that third parties rather willing to invest their time in building further integrations. It is important for the Open Integration Hub acceptance to find a common API documentation format, therefore. Renat @zubairov mentioned the [open data](http://www.odata.org/) initiative in this context, as an approach for proprietary APIs. 

These tasks were derived from the MS2 planning workshop [protocol](https://github.com/openintegrationhub/Data-and-Domain-Models/blob/460d573719ba208af5db36bf3457f576785b5497/Protocols/2018-01-17Workshop.md#next-steps--derived-tasks). Our goal is to accomplish POC1 of that [roadmap](https://github.com/openintegrationhub/Architecture/blob/d58e8b1750022d95c5339ed39502d9d77b1166e1/Roadmap/RoadmapV1.md#poc-1--point-to-point-integration-of-isv-applications). The following criteria had been found during the workshop in order to do so:

- [ ] Create a mapping table #47 / #62
- [ ] Create JSONata expression (mapping) #46 / #61
- [ ] Document which Elastic components where used and why
- [ ] Create an [interface](http://www.odata.org/) documentation #45 / #60
- [ ] Compare the documentation in order to unify them
