### ISSUE TITLE
Describe the standard data fields semantically

### ISSUE THREAD

**Issue by RaphaelKomander** [openintegrationhub/Data-and-Domain-Models#50]
All semantic field mappings from proprietary data models towards the standard data model (model configuration) should be able to be done by hand. A third party needs to understand the usage of every single standard data field so that mismatches become less likely. 

Such vulnerable implementations would harm a seamless data flow. A proper implementation needs to rely on identical mappings of all other integrations. Therefore a detailed descriptions of the standard data fields are mandatory.

- [ ] Quality criteria for the description
- [ ] Generic procedure model - later extensions
- [ ] Affect on aggregates - usage context implicit
