### ISSUE TITLE
Accomplish the adapter quality guidelines

### ISSUE THREAD

**Issue by RaphaelKomander** [openintegrationhub/Data-and-Domain-Models#52]
According to the [protocol](https://github.com/openintegrationhub/Data-and-Domain-Models/blob/460d573719ba208af5db36bf3457f576785b5497/Protocols/2018-01-17Workshop.md#next-steps--derived-tasks) of the MS2 planning workshop, the Adapters of Snazzy Contacts and SilverERP would correspond to the criteria of POC2, if the [quality guidelines](https://github.com/openintegrationhub/Connectors/blob/master/Adapters/AdapterOperationTypes.md) have been accomplished.

- [X] Upload the Adapter to GitHub
   - [X] [SnazzyContacts](https://github.com/openintegrationhub/Data-and-Domain-Models/tree/master/MasterDataModels/SnazzyContactsAdapter)
   - [X] [SilverERP](https://github.com/openintegrationhub/Data-and-Domain-Models/tree/master/MasterDataModels/SilverpContactsAdapter)
   - [X] [WiceCRM](https://github.com/openintegrationhub/Data-and-Domain-Models/tree/master/MasterDataModels/WiceAdapter)
- [ ] Fulfil the [Adapter Checklists](https://github.com/openintegrationhub/Connectors/tree/master/Adapters/AdapterChecklists)
- [ ] Feedback hands-on experiences with the guide - #20
